<?xml version="1.0" encoding="utf-8"?><Database Name="OOSD_db" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RG39F3G\MINHTHONGSQL;Initial Catalog=OOSD_db;Integrated Security=True" SettingsObjectName="OOSD_Login.Properties.Settings" SettingsPropertyName="OOSD_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Group_Right" Member="Group_Rights">
    <Type Name="Group_Right">
      <Column Name="GroupID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="RightID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Right_tb_Group_Right" Member="Right_tb" ThisKey="RightID" OtherKey="RightID" Type="Right_tb" IsForeignKey="true" />
      <Association Name="UserGroup_Group_Right" Member="UserGroup" ThisKey="GroupID" OtherKey="GroupID" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="username" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GroupID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="User_User_Right" Member="User_Rights" ThisKey="username" OtherKey="username" Type="User_Right" />
      <Association Name="UserGroup_User" Member="UserGroup" ThisKey="GroupID" OtherKey="GroupID" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Right_tb" Member="Right_tbs">
    <Type Name="Right_tb">
      <Column Name="RightID" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RightName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Right_tb_Group_Right" Member="Group_Rights" ThisKey="RightID" OtherKey="RightID" Type="Group_Right" />
      <Association Name="Right_tb_User_Right" Member="User_Rights" ThisKey="RightID" OtherKey="RightID" Type="User_Right" />
    </Type>
  </Table>
  <Table Name="dbo.User_Right" Member="User_Rights">
    <Type Name="User_Right">
      <Column Name="username" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="RightID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Right_tb_User_Right" Member="Right_tb" ThisKey="RightID" OtherKey="RightID" Type="Right_tb" IsForeignKey="true" />
      <Association Name="User_User_Right" Member="User" ThisKey="username" OtherKey="username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroup" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="GroupID" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="UserGroup_Group_Right" Member="Group_Rights" ThisKey="GroupID" OtherKey="GroupID" Type="Group_Right" />
      <Association Name="UserGroup_User" Member="Users" ThisKey="GroupID" OtherKey="GroupID" Type="User" />
    </Type>
  </Table>
</Database>